name: MiMoMac
options:
  bundleIdPrefix: com.mimo
  deploymentTarget:
    macOS: "13.0"

targets:
  MiMoMac:
    type: application
    platform: macOS
    sources:
      - MiMoMac
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mimo.MiMoMac
        PRODUCT_NAME: "MiMo AI"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: MiMoMac/Info.plist
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_CFBundleDisplayName: "MiMo AI"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2024 MiMo AI"
        SWIFT_VERSION: "5.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        ENABLE_HARDENED_RUNTIME: YES
